export default [
    {
      bg: '#87ceeb',
      color: '#000000',
      category: 'Basic Information',
      subCategories: ['Skincare', 'Personal care', 'Health', 'Eye care'],
    },
    {
      bg: '#87ceeb',
      color: '#000000',
      category: 'Parents Information',
      subCategories: [
        'Fruits & Vegetables',
        'Frozen Food',
        'Bakery',
        'Snacks & Desserts',
        'Beverages',
        'Alcoholic beverages',
        'Noodles & Pasta',
        'Rice & Cooking oil',
      ],
    },
    {
      bg: '#87ceeb',
      color: '#000000',
      category: 'Personal Details',
      subCategories: ['Skincare', 'Makeup', 'Nail care', 'Perfume'],
    },
    {
      bg: '#87ceeb',
      color: '#000000',
      category: 'Address',
      subCategories: [
        'Toys',
        'Trolleys',
        'LEGO®',
        'Electronics',
        'Puzzles',
        'Costumes',
        'Food',
        'Hygiene & Care',
        "Child's room",
        'Feeding accessories',
      ],
    },
    {
      bg: '#87ceeb',
      color: '#000000',
      category: 'Educational Details',
      subCategories: [
        'Air purifiers',
        'Stoves, hoods & ovens',
        'Refrigerators',
        'Coffee & Tea',
        'Air conditioning',
        'Grilling',
        'Vacuum cleaners',
      ],
    },
  ];